cargo-features = ["edition"]

[package]
edition = '2018'
name = "webapp"
version = "0.1.0"
authors = ["Michael Singh <michael@wadadli.me>"]

[dependencies]
iron = "0.6.0"
mysql = "14.0.0"
chrono = "0.4"
clap = "2"
